apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-into-particular-node-deployment
  labels:
    project: strategy
spec:
  selector:
    matchLabels:
      project: strategy
  template:
    metadata:
      name: first-pod
      labels:
        project: strategy
    spec:
      nodeName: gk3-cluster-one-pool-2-7434a2e1-b5xw
      containers:
      - name: first-container
        image: httpd
