apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    project: strategy
spec:
  selector:
    matchLabels:
      project: strategy
  template:
    metadata:
      name: first-pod
      labels:
        project: strategy
    spec:
      containers:
      - name: first-container
        image: httpd
        envFrom:
        - secretRef:
            name: first-secret
        - configMapRef:
            name: first-cm
